(function(){
const D=window.MAKERS_DATA||{}, Y=window.MAKERS_2026||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const teamByManager=m=>{const f=(D.franchises||[]).find(x=>x.manager===m);return f?f.current:m};
const managerByTeam=t=>{const f=(D.franchises||[]).find(x=>x.current===t);if(f)return f.manager;const c=(D.currentTeams||[]).find(x=>x[0]===t);return c?c[1]:t};
const meta=t=>(Y.teamMeta||{})[t]||{abbr:String(t).split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase(),color:'#6b2720',logo:''};
function badge(t,size='md'){const m=meta(t);return m.logo?`<span class="team-mark ${size}" style="--team:${esc(m.color)}"><img src="${esc(m.logo)}" alt=""></span>`:`<span class="team-mark ${size}" style="--team:${esc(m.color)}">${esc(m.abbr)}</span>`}
function currentStandings(){return (Y.standings||[]).map(x=>({...x,gp:(x.w||0)+(x.l||0),pct:(x.w||0)/(((x.w||0)+(x.l||0))||1)})).sort((a,b)=>b.w-a.w||b.pf-a.pf||((PRE?.[b.team]??0)-(PRE?.[a.team]??0))||a.manager.localeCompare(b.manager)).map((x,i)=>({...x,seed:i+1}))}
function realResults(){return (Y.results||[]).filter(x=>x&&x.status!=='DEMO')}
function allGames(){return [...(D.gameLog||[]),...realResults().map(x=>({year:2026,week:x.week||null,round:x.round||`Week ${x.week||''}`,stage:x.stage||'Regular Season',teamA:x.teamA||x.home,managerA:x.managerA||managerByTeam(x.teamA||x.home),scoreA:Number(x.scoreA??x.homeScore),teamB:x.teamB||x.away,managerB:x.managerB||managerByTeam(x.teamB||x.away),scoreB:Number(x.scoreB??x.awayScore)}))]}
function series(ma,mb){let w=0,l=0,regW=0,regL=0,postW=0,postL=0;for(const g of allGames()){if(g.managerA===ma&&g.managerB===mb){if(g.scoreA>g.scoreB){w++;g.stage==='Regular Season'?regW++:postW++}else{l++;g.stage==='Regular Season'?regL++:postL++}}else if(g.managerA===mb&&g.managerB===ma){if(g.scoreB>g.scoreA){w++;g.stage==='Regular Season'?regW++:postW++}else{l++;g.stage==='Regular Season'?regL++:postL++}}}return {w,l,regW,regL,postW,postL}}
function meetings(ma,mb){return allGames().filter(g=>(g.managerA===ma&&g.managerB===mb)||(g.managerA===mb&&g.managerB===ma)).sort((a,b)=>b.year-a.year||((b.week||99)-(a.week||99)))}
function meetingLine(g,ma){if(!g)return 'No archived meeting yet.';const myA=g.managerA===ma, myScore=myA?g.scoreA:g.scoreB, oppScore=myA?g.scoreB:g.scoreA, opp=myA?g.managerB:g.managerA;return `${g.year} ${g.round}: ${ma} ${myScore.toFixed(2)}–${oppScore.toFixed(2)} ${opp}`}
function matchupHistory(teamA,teamB){const ma=managerByTeam(teamA),mb=managerByTeam(teamB),s=series(ma,mb),ms=meetings(ma,mb),prev=ms[0];let biggest=null;for(const g of ms){const diff=Math.abs(g.scoreA-g.scoreB);if(!biggest||diff>biggest.diff)biggest={g,diff}};let streak='—';if(ms.length){const winner=g=>g.scoreA>g.scoreB?g.managerA:g.managerB,who=winner(ms[0]);let n=0;for(const g of ms){if(winner(g)===who)n++;else break}streak=`${who} W${n}`}let rivalry='Fresh beef';const total=s.w+s.l;if(total>=8&&Math.abs(s.w-s.l)<=2)rivalry='Old-school rivalry';else if(total>=7)rivalry='Plenty of receipts';else if(total>=4)rivalry='Building history';let biggestText='No archived margin';if(biggest){const g=biggest.g,winner=g.scoreA>g.scoreB?g.managerA:g.managerB;biggestText=`${g.year} ${g.round} · ${winner} by ${biggest.diff.toFixed(2)}`}return {ma,mb,...s,total,previous:meetingLine(prev,ma),previousRaw:prev,biggest:biggestText,streak,rivalry}}
function preseasonStrengths(){const vals=(D.currentTeams||[]).map(x=>Number(x[4]));const lo=Math.min(...vals),hi=Math.max(...vals);let out={};for(const r of D.currentTeams||[]){const yp=(Number(r[4])-lo)/(hi-lo||1);out[r[0]]=yp}return out}
const PRE=preseasonStrengths();
function winProb(a,b){const sa=PRE[a]??.5,sb=PRE[b]??.5;return 1/(1+Math.exp(-(sa-sb)*0.85))}
function powerMetrics(){const st=currentStandings(), maxPF=Math.max(1,...st.map(x=>x.pf||0)), maxGP=Math.max(0,...st.map(x=>x.gp||0));let rows=st.map(x=>{const pre=PRE[x.team]??.5;const record=x.gp?x.pct:.5;const scoring=x.gp?(x.pf/maxPF):.5;const liveWeight=clamp(x.gp/6,0,.72);const index=100*(pre*(1-liveWeight)+(0.58*record+0.42*scoring)*liveWeight);return {...x,powerIndex:index}}).sort((a,b)=>b.powerIndex-a.powerIndex);return rows.map((x,i)=>({...x,powerRank:i+1}))}
function streaks(){const gs=realResults().filter(g=>(g.stage||'Regular Season')==='Regular Season').sort((a,b)=>(a.week||0)-(b.week||0));const out={};for(const s of Y.standings||[])out[s.manager]='—';for(const s of Y.standings||[]){const mine=gs.filter(g=>[g.managerA||managerByTeam(g.teamA||g.home),g.managerB||managerByTeam(g.teamB||g.away)].includes(s.manager));let type=null,n=0;for(let i=mine.length-1;i>=0;i--){const g=mine[i],a=(g.managerA||managerByTeam(g.teamA||g.home))===s.manager,sc1=Number(a?(g.scoreA??g.homeScore):(g.scoreB??g.awayScore)),sc2=Number(a?(g.scoreB??g.awayScore):(g.scoreA??g.homeScore)),t=sc1>sc2?'W':'L';if(type===null){type=t;n=1}else if(t===type)n++;else break}if(type)out[s.manager]=type+n}return out}
function scheduleFor(team,fromWeek=1,toWeek=14){let arr=[];for(let w=fromWeek;w<=toWeek;w++){const g=(D.schedule2026?.[String(w)]||[]).find(x=>x.includes(team));if(g)arr.push({week:w,opp:g[0]===team?g[1]:g[0]})}return arr}
function remainingSOS(team){const played=new Set(realResults().filter(x=>(x.stage||'Regular Season')==='Regular Season').map(x=>`${x.week}|${[x.teamA||x.home,x.teamB||x.away].sort().join('|')}`));const rank=Object.fromEntries(powerMetrics().map(x=>[x.team,x.powerRank]));let rs=scheduleFor(team).filter(x=>!played.has(`${x.week}|${[team,x.opp].sort().join('|')}`));return rs.length?rs.reduce((a,x)=>a+(rank[x.opp]||10),0)/rs.length:null}
function rng(seed=20260901){let x=seed|0;return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return ((x>>>0)%1000000)/1000000}}
let SIMCACHE=null;
function simulate(n=24000){if(SIMCACHE)return SIMCACHE;const rand=rng(), st=currentStandings(), teams=st.map(x=>x.team), base=Object.fromEntries(st.map(x=>[x.team,{w:x.w,l:x.l,pf:x.pf,pa:x.pa}]));const completed=new Set(realResults().filter(x=>(x.stage||'Regular Season')==='Regular Season').map(x=>`${x.week}|${[x.teamA||x.home,x.teamB||x.away].sort().join('|')}`));const remaining=[];for(let w=1;w<=14;w++)for(const [a,b] of D.schedule2026?.[String(w)]||[])if(!completed.has(`${w}|${[a,b].sort().join('|')}`))remaining.push([a,b]);const out=Object.fromEntries(teams.map(t=>[t,{playoff:0,bye:0,title:0,toilet:0,seedSum:0,seeds:Array(11).fill(0)}]));const game=(a,b)=>rand()<winProb(a,b)?a:b;
for(let z=0;z<n;z++){let rec=Object.fromEntries(teams.map(t=>[t,{...base[t]}]));for(const [a,b] of remaining){const winner=game(a,b),loser=winner===a?b:a;rec[winner].w++;rec[loser].l++;const sa=92+60*(PRE[a]??.5)+32*(rand()-.5),sb=92+60*(PRE[b]??.5)+32*(rand()-.5);rec[a].pf+=sa;rec[b].pf+=sb;rec[a].pa+=sb;rec[b].pa+=sa}const seeds=[...teams].sort((a,b)=>rec[b].w-rec[a].w||rec[b].pf-rec[a].pf||a.localeCompare(b));seeds.forEach((t,i)=>{out[t].seedSum+=i+1;out[t].seeds[i+1]++;if(i<6)out[t].playoff++;if(i<2)out[t].bye++});const s=i=>seeds[i-1];const q1=game(s(3),s(6)),q2=game(s(4),s(5));const sf1=game(s(1),q2),sf2=game(s(2),q1),champ=game(sf1,sf2);out[champ].title++;const tb1=game(s(7),s(10)),tb2=game(s(8),s(9));const loser1=tb1===s(7)?s(10):s(7),loser2=tb2===s(8)?s(9):s(8);const escape=game(loser1,loser2),toilet=escape===loser1?loser2:loser1;out[toilet].toilet++}
const res=teams.map(t=>{let q=out[t];let cum=0,lo=1,hi=10;for(let i=1;i<=10;i++){cum+=q.seeds[i];if(cum/n>=.1){lo=i;break}}cum=0;for(let i=1;i<=10;i++){cum+=q.seeds[i];if(cum/n>=.9){hi=i;break}}return {team:t,manager:managerByTeam(t),playoff:+(100*q.playoff/n).toFixed(1),bye:+(100*q.bye/n).toFixed(1),title:+(100*q.title/n).toFixed(1),toilet:+(100*q.toilet/n).toFixed(1),avgSeed:+(q.seedSum/n).toFixed(2),seedLow:lo,seedHigh:hi}});SIMCACHE=res;return res}
function clinchInfo(team){const st=currentStandings(),me=st.find(x=>x.team===team),seventh=st[6],sixth=st[5];if(!me)return {};const games=14,playoffMagic=Math.max(0,games+1-me.w-(seventh?.l||0)),elim=Math.max(0,games+1-(sixth?.w||0)-me.l);const rem=games-me.gp;return {remaining:rem,playoffMagic:playoffMagic<=rem?playoffMagic:null,elimination:elim<=rem?elim:null}}
function projectedField(sim=simulate()){return [...sim].sort((a,b)=>a.avgSeed-b.avgSeed)}
function likelyOpponent(team,sim=simulate()){const f=projectedField(sim),idx=f.findIndex(x=>x.team===team)+1;if(idx<=0)return '—';if(idx===1)return `Bye → likely seed 4/5 semifinal`;if(idx===2)return `Bye → likely seed 3/6 semifinal`;if(idx===3)return `Projected vs ${f[5]?.team||'seed 6'}`;if(idx===4)return `Projected vs ${f[4]?.team||'seed 5'}`;if(idx===5)return `Projected vs ${f[3]?.team||'seed 4'}`;if(idx===6)return `Projected vs ${f[2]?.team||'seed 3'}`;return 'Toilet Bowl field'}
function teamNeed(team,simrow){const st=currentStandings(),me=st.find(x=>x.team===team),rem=14-(me?.gp||0);if(!me)return '';if(rem===0)return me.seed<=6?(me.seed<=2?'First-round bye secured.':'Championship bracket secured.'):'Toilet Bowl territory.';if(simrow.playoff>=80)return 'Protect position and chase a top-two bye.';if(simrow.playoff>=55)return 'Stay above the cut line; every points-for tiebreaker matters.';if(simrow.playoff>=30)return 'Needs wins now and help around the six-seed line.';return 'Needs a run before the playoff race gets away.'}
function implications(a,b){const st=currentStandings(),ma=st.find(x=>x.team===a),mb=st.find(x=>x.team===b),gp=Math.max(ma?.gp||0,mb?.gp||0);if(gp<5)return 'No clinch math yet — this is about building the record and points-for cushion that matters later.';if(gp<11)return 'Middle-of-season leverage: a win can swing the projected seed range and tighten the race around the cut line.';return 'Every result now hits the playoff cut, bye race and Toilet Bowl picture directly.'}
function renderScoreboard(week=1,compact=false){const board=(Y.liveScoring&&Number(Y.liveScoring.week)===Number(week))?Y.liveScoring:((Y.scoreboardDemo&&Number(Y.scoreboardDemo.week)===Number(week))?Y.scoreboardDemo:null);if(!board)return '';
const cards=(board.matchups||[]).map(g=>{const hs=Number(g.homeScore||0),as=Number(g.awayScore||0),hp=Number(g.homeProj||0),ap=Number(g.awayProj||0),status=String(g.status||'UPCOMING').toUpperCase(),close=status==='LIVE'&&Math.abs(hp-ap)<=6,upset=status==='LIVE'&&((g.homeWinProb<40&&hs>as)||(g.homeWinProb>60&&as>hs)),winner=status==='FINAL'?(hs>as?'home':'away'):'';return `<article class="score-card ${status.toLowerCase()}${close?' close':''}${upset?' upset':''}"><div class="score-top"><span class="score-status">${esc(status)}</span>${close?'<span class="score-flag">CLOSE</span>':''}${upset?'<span class="score-flag upsetflag">UPSET WATCH</span>':''}</div><div class="score-team ${winner==='home'?'winner':''}">${badge(g.home,'sm')}<div><b>${esc(g.home)}</b><small>Proj ${hp.toFixed(1)}</small></div><strong>${status==='UPCOMING'?'—':hs.toFixed(2)}</strong></div><div class="score-team ${winner==='away'?'winner':''}">${badge(g.away,'sm')}<div><b>${esc(g.away)}</b><small>Proj ${ap.toFixed(1)}</small></div><strong>${status==='UPCOMING'?'—':as.toFixed(2)}</strong></div><div class="win-meter"><span style="width:${clamp(Number(g.homeWinProb??50),0,100)}%"></span></div><div class="score-detail"><span>${esc(g.detail||'')}</span><b>Projected: ${esc(hp>=ap?g.home:g.away)}</b></div></article>`}).join('');return `<section class="section scoreboard-section"><div class="wrap"><div class="scoreboard-banner"><div><div class="kicker">${esc(board.label||'LIVE SCORES')}</div><h2>${board.mode==='demo'?'Week 1 live-scoring preview':`Week ${week} scoreboard`}</h2></div><p>${esc(board.lastUpdated||'')}</p></div><div class="score-grid${compact?' compact':''}">${cards}</div>${board.mode==='demo'?'<div class="demo-note"><b>Demo only.</b> These scores exist to preview live, close-game, upset-watch, upcoming and final states. They are not league results and are excluded from standings, records and odds.</div>':''}</div></section>`}
function renderMatchupCard(week,a,b){const h=matchupHistory(a,b), p=(D.weeklyPreview?.[String(week)]||[]).find(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a)), pa=p?(p.favorite===a?p.prob:100-p.prob):100*winProb(a,b),pb=100-pa;return `<article class="matchup-pro"><div class="matchup-pro-head"><span class="rivalry-tag">${esc(h.rivalry)}</span><span>WEEK ${week}</span></div><div class="matchup-pro-teams"><div>${badge(a)}<b>${esc(a)}</b><small>${esc(h.ma)}</small><strong>${pa.toFixed(1)}%</strong></div><div class="matchup-vs">VS</div><div>${badge(b)}<b>${esc(b)}</b><small>${esc(h.mb)}</small><strong>${pb.toFixed(1)}%</strong></div></div><div class="upset-meter"><span style="width:${pa}%"></span></div><div class="matchup-history-grid"><div><small>ALL-TIME H2H</small><b>${esc(h.ma)} ${h.w}-${h.l} ${esc(h.mb)}</b></div><div><small>SERIES STREAK</small><b>${esc(h.streak)}</b></div><div><small>PREVIOUS MEETING</small><b>${esc(h.previous)}</b></div><div><small>LARGEST ARCHIVED WIN</small><b>${esc(h.biggest)}</b></div><div><small>UPSET CHANCE</small><b>${(Math.min(pa,pb)).toFixed(1)}% for ${esc(pa<pb?a:b)}</b></div><div><small>PLAYOFF IMPLICATION</small><b>${esc(implications(a,b))}</b></div></div></article>`}
function postseasonBracket(){const st=currentStandings();const regularDone=st.every(x=>x.gp>=14);const seedSource=regularDone?st:projectedField().map((x,i)=>({team:x.team,manager:x.manager,seed:i+1}));const s=n=>seedSource[n-1];const label=regularDone?'OFFICIAL SEEDS':'PROJECTED FIELD';return `<section class="section postseason-section"><div class="wrap"><div class="section-head"><div><div class="kicker">${label}</div><h2>2026 postseason bracket</h2></div><p class="section-intro">Top six chase the title. Bottom four enter the Toilet Bowl.</p></div>${!regularDone?'<div class="notice"><b>Projection only.</b> This bracket becomes official when the 14-game regular season is complete.</div>':''}<div class="bracket-grid"><div class="bracket-col"><h3>Week 15 · Quarterfinals</h3><div class="bracket-game"><span>#3 ${esc(s(3)?.team||'TBD')}</span><b>vs</b><span>#6 ${esc(s(6)?.team||'TBD')}</span></div><div class="bracket-game"><span>#4 ${esc(s(4)?.team||'TBD')}</span><b>vs</b><span>#5 ${esc(s(5)?.team||'TBD')}</span></div><div class="bye-box">#1 ${esc(s(1)?.team||'TBD')} · BYE</div><div class="bye-box">#2 ${esc(s(2)?.team||'TBD')} · BYE</div></div><div class="bracket-col"><h3>Week 16 · Semifinals</h3><div class="bracket-game"><span>#1 seed</span><b>vs</b><span>4/5 winner</span></div><div class="bracket-game"><span>#2 seed</span><b>vs</b><span>3/6 winner</span></div></div><div class="bracket-col"><h3>Week 17 · Championship</h3><div class="bracket-game final"><span>Semifinal winner</span><b>vs</b><span>Semifinal winner</span></div></div></div><div class="toilet-wrap"><div class="kicker">TOILET BOWL</div><h3>Lose twice and the shame is yours</h3><div class="bracket-grid toilet"><div class="bracket-col"><h3>Week 15</h3><div class="bracket-game"><span>#7 ${esc(s(7)?.team||'TBD')}</span><b>vs</b><span>#10 ${esc(s(10)?.team||'TBD')}</span></div><div class="bracket-game"><span>#8 ${esc(s(8)?.team||'TBD')}</span><b>vs</b><span>#9 ${esc(s(9)?.team||'TBD')}</span></div></div><div class="bracket-col"><h3>Week 16 · Toilet Bowl</h3><div class="bracket-game final"><span>Semifinal loser</span><b>vs</b><span>Semifinal loser</span></div></div><div class="bracket-col"><h3>Week 17</h3><div class="bye-box">Placement games + championship weekend</div></div></div></div></div></section>`}
function renderWarRoomIntel(){const sim=simulate(),pow=powerMetrics(),stk=streaks(),by=Object.fromEntries(sim.map(x=>[x.team,x]));const rows=pow.map(x=>{const o=by[x.team],ci=clinchInfo(x.team),sos=remainingSOS(x.team);return `<tr><td>${x.seed}</td><td>${badge(x.team,'xs')} <b>${esc(x.team)}</b><div class="small">${esc(x.manager)} · ${stk[x.manager]}</div></td><td><b>${x.w}-${x.l}</b></td><td>${x.powerIndex.toFixed(1)}</td><td>${sos==null?'—':sos.toFixed(2)}</td><td>${o.seedLow}–${o.seedHigh}</td><td>${o.playoff}%</td><td>${ci.playoffMagic??'—'}</td><td>${ci.elimination??'—'}</td><td>${esc(likelyOpponent(x.team,sim))}</td></tr>`}).join('');const cards=pow.map(x=>{const o=by[x.team],ci=clinchInfo(x.team);return `<div class="war-card">${badge(x.team)}<div><div class="kicker">${esc(x.manager)} · POWER #${x.powerRank}</div><h3>${esc(x.team)}</h3><p>${esc(teamNeed(x.team,o))}</p><div class="scenario-line">${ci.playoffMagic!=null?`<b>Clinch:</b> ${ci.playoffMagic} combined team wins / 7th-place losses`:ci.elimination!=null?`<b>Elimination:</b> ${ci.elimination} combined team losses / 6th-place wins`:'Clinch and elimination numbers are not in range yet.'}</div><div class="war-chips"><span>${o.playoff}% playoffs</span><span>${o.bye}% bye</span><span>${o.title}% title</span><span>${o.toilet}% toilet</span></div></div></div>`}).join('');return `<section class="section alt"><div class="wrap"><div class="section-head"><div><div class="kicker">PLAYOFF COMMAND CENTER</div><h2>What everybody needs</h2></div><p class="section-intro">Current record, remaining schedule, seed range and bracket path in one place.</p></div><div class="war-grid">${cards}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">THE MATH</div><h2>Race dashboard</h2></div></div><div class="table-wrap"><table><thead><tr><th>Seed</th><th>Team</th><th>Record</th><th>Power</th><th>Remaining SOS*</th><th>Seed range</th><th>Playoffs</th><th>Magic</th><th>Elim.</th><th>Likely first opponent</th></tr></thead><tbody>${rows}</tbody></table></div><p class="tiny">*Remaining SOS is average opponent power rank; lower is harder. Magic and elimination numbers appear once they are mathematically in range.</p></div></section>`}
function leaderboardRows(){const rec=(D.records||[]).map(r=>{const cur=(Y.standings||[]).find(s=>s.manager===r.manager);const w=r.w+(cur?.w||0),l=r.l+(cur?.l||0),pf=r.pf+(cur?.pf||0);return {...r,w,l,pf,pct:w/(w+l||1),playoffWins:(D.playoffWL?.[r.manager]||[0,0])[0]}});return {wins:[...rec].sort((a,b)=>b.w-a.w),pct:[...rec].filter(x=>x.w+x.l>=20).sort((a,b)=>b.pct-a.pct),pf:[...rec].sort((a,b)=>b.pf-a.pf),titles:[...rec].sort((a,b)=>b.titles-a.titles||b.finals-a.finals),playoffs:[...rec].sort((a,b)=>b.playoffWins-a.playoffWins),moves:[...rec].sort((a,b)=>b.moves-a.moves)}}
function recordWatch(){const gs=allGames(), high=[...gs].sort((a,b)=>Math.max(b.scoreA,b.scoreB)-Math.max(a.scoreA,a.scoreB))[0],low=[...gs].sort((a,b)=>Math.min(a.scoreA,a.scoreB)-Math.min(b.scoreA,b.scoreB))[0],margin=[...gs].sort((a,b)=>Math.abs(b.scoreA-b.scoreB)-Math.abs(a.scoreA-a.scoreB))[0];const fmt=(g,kind)=>{if(!g)return '—';if(kind==='high'){const a=g.scoreA>=g.scoreB;return `${g.year} ${g.round} · ${a?g.managerA:g.managerB} ${Math.max(g.scoreA,g.scoreB).toFixed(2)}`}if(kind==='low'){const a=g.scoreA<=g.scoreB;return `${g.year} ${g.round} · ${a?g.managerA:g.managerB} ${Math.min(g.scoreA,g.scoreB).toFixed(2)}`}return `${g.year} ${g.round} · ${Math.abs(g.scoreA-g.scoreB).toFixed(2)} pts`};return {high:fmt(high,'high'),low:fmt(low,'low'),margin:fmt(margin,'margin')}}
window.MAKERS_ENGINE={esc,badge,meta,managerByTeam,teamByManager,currentStandings,allGames,series,meetings,matchupHistory,powerMetrics,streaks,remainingSOS,simulate,clinchInfo,likelyOpponent,teamNeed,implications,renderScoreboard,renderMatchupCard,postseasonBracket,renderWarRoomIntel,leaderboardRows,recordWatch};
})();
