(function(){
'use strict';
const D=window.MAKERS_DATA||{}, T=window.MAKERS_TUESDAY||{}, Q=new URLSearchParams(location.search);
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=(v,d=2)=>Number(v||0).toFixed(d);
const navLinks=[['weeks.html','Write-Ups'],['season-2026.html','2026'],['predictions.html','Predictions'],['analytics.html','Analytics'],['schedule.html','Schedule'],['trophy-case.html','Trophies'],['history.html','History'],['franchises.html','Franchises'],['head-to-head.html','H2H'],['drafts.html','Draft'],['transactions.html','Moves'],['waiver-wire.html','Waivers'],['keepers.html','Keepers'],['power-rankings.html','Power'],['playoff-odds.html','Odds'],['records.html','Records'],['wall-of-shame.html','Shame']];
function nav(){return `<header class="topbar"><div class="wrap"><a class="brand" href="index.html"><span class="brandmark">M</span><span>THE MAKERS</span></a><button class="hamb" aria-label="Open navigation">☰</button><nav class="nav">${navLinks.map(x=>`<a href="${x[0]}">${x[1]}</a>`).join('')}</nav></div></header>`}
function foot(){return `<footer class="footer"><div class="wrap"><div><strong>The Makers</strong><div class="small">Fantasy football, since 2003.</div></div><div class="small">Tuesday close · Week 1 final · Week 2 early board.</div></div></footer>`}
function hero(t,c='',ey='THE MAKERS · SINCE 2003'){return `<section class="pagehead"><div class="wrap"><div class="eyebrow">${e(ey)}</div><h1>${e(t)}</h1><p>${e(c)}</p></div></section>`}
function sec(t,h,i='',ey=''){return `<section class="section"><div class="wrap"><div class="section-head"><div>${ey?`<div class="kicker">${e(ey)}</div>`:''}<h2>${e(t)}</h2></div>${i?`<p class="section-intro">${e(i)}</p>`:''}</div>${h}</div></section>`}
function card(t,b,ey=''){return `<div class="card">${ey?`<div class="kicker">${e(ey)}</div>`:''}<h3>${e(t)}</h3><p>${b}</p></div>`}
function standing(m){return T.standings.find(x=>x.manager===m)}
function power(m){return T.power.find(x=>x.manager===m)}
function odds(m){return T.odds.find(x=>x.manager===m)}
function need(m){return T.needs.find(x=>x.manager===m)}
function movement(v){return v>0?`▲ ${v}`:v<0?`▼ ${Math.abs(v)}`:'—'}
function barRows(field){return [...T.odds].sort((a,b)=>b[field]-a[field]).map(x=>`<div class="odds-row"><strong>${e(x.team)}<small>${e(standing(x.manager)?.record||'')}</small></strong><div class="bar"><span style="width:${Math.min(100,x[field])}%"></span></div><b>${f(x[field],1)}%</b></div>`).join('')}
function resultForTeam(team){for(const g of T.receiptGames){if(g.teamA===team)return {opp:g.teamB,for:g.scoreA,against:g.scoreB,result:g.scoreA>g.scoreB?'W':'L'};if(g.teamB===team)return {opp:g.teamA,for:g.scoreB,against:g.scoreA,result:g.scoreB>g.scoreA?'W':'L'}}return null}
function week2ForTeam(team){for(const g of T.week2Yahoo){if(g.teamA===team)return {opp:g.teamB,proj:g.projA,oppProj:g.projB};if(g.teamB===team)return {opp:g.teamA,proj:g.projB,oppProj:g.projA}}return null}
function managerForTeam(team){return T.standings.find(x=>x.team===team)?.manager||D.franchises?.find(x=>x.current===team)?.manager||team}
function storyCards(){return `<div class="grid two">${T.storylines.map((s,i)=>card(s.title,e(s.copy),`STORYLINE ${i+1}`)).join('')}</div>`}
function awards(){return `<div class="grid two">${T.awards.map(a=>card(a.winner,e(a.copy),a.award)).join('')}</div>`}
function finalCards(){return `<div class="grid two">${T.gameRecaps.map(g=>`<article class="card"><div class="kicker">${e(g.label)}</div><h3>${e(g.a)} ${f(g.sa)} — ${f(g.sb)} ${e(g.b)}</h3><p>${e(g.copy)}</p></article>`).join('')}</div>`}
function currentPowerTable(){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>Record</th><th>Power Index</th><th>Pre</th><th>Move</th><th>W2 Yahoo</th></tr></thead><tbody>${T.power.map(x=>`<tr><td><b>${x.rank}</b></td><td><b>${e(x.team)}</b><div class="small">${e(x.manager)}</div></td><td>${e(x.record)}</td><td><b>${f(x.index,1)}</b></td><td>#${x.preRank}</td><td>${e(movement(x.movement))}</td><td>${f(x.w2Proj)}</td></tr>`).join('')}</tbody></table></div>`}
function home(){let trophies=Object.entries(D.seasons||{}).map(([y,s])=>card(`${y} — ${s.champion}`,`<b>${e(s.champManager)}</b><br><span class="small">Runner-up: ${e(s.runnerManager)} · ${e(s.runnerUp)}</span>`,'CHAMPION')).join('');return `<section class="hero"><div class="wrap"><div class="eyebrow">2026 WEEK 2 · TUESDAY CLOSE</div><h1>The Makers<br><em style="color:var(--gold);font-weight:400">Week 1 Receipts</em></h1><p>Week 1 is final. TomD broke the modern-era scoring record, Billy beat both prediction systems, and the first Week 2 Yahoo board is live.</p><div class="hero-actions"><a class="btn primary" href="week.html?week=1">Week 1 Results Recap</a><a class="btn ghost" href="season-2026.html">Race Dashboard</a><a class="btn ghost" href="waiver-wire.html">Tuesday Waivers</a></div></div></section>`+sec('Season storylines',storyCards(),'These move every Tuesday as the season gives us new evidence.','THE LIVE SEASON')+sec('Week 1 results recap',`<article class="home-weekly-feature"><div class="home-weekly-copy"><div class="home-weekly-meta"><span>WEEK 1</span><span>RESULTS RECAP</span></div><h3>${e(T.headline)}</h3><p>${e(T.recapIntro)}</p><div class="home-weekly-actions"><a class="btn primary" href="week.html?week=1">Read the full recap</a><a class="home-archive-link" href="weeks.html">All write-ups →</a></div></div><aside class="home-weekly-side"><div class="kicker">GAME OF THE WEEK</div><h4>${e(T.gameOfWeek)}</h4><p>Chris survived Adam by 5.70 in the closest finish of the week.</p><div class="home-weekly-side-rule"></div><div class="kicker">RECORD WATCH</div><p>TomD's 187.86 is the new modern-era regular-season weekly scoring record.</p></aside></article>`,'Tuesday closes the previous week; Thursday will replace the featured current item with the Week 2 preview while this recap stays archived.','FROM THE LEAGUE DESK')+sec("Not Yahoo's rankings",currentPowerTable(),T.powerMethod,'TUESDAY POWER INDEX')+sec('The story so far',`<div class="grid four">${trophies}</div>`,'Four completed modern-era championships. The 2026 chapter now has its first receipts.','THE TROPHY SHELF')}
function weeks(){let cards='';for(let w=1;w<=17;w++){let status=w===1?'Results Recap':w===2?'Thursday Preview Pending':'Scheduled';let headline=w===1?T.headline:w===2?'Week 2 early Yahoo board is live; Makers picks lock Thursday.':'Write-up pending';cards+=`<a class="week-card${w===2?' current':''}" href="week.html?week=${w}"><div class="week-status">${e(status)}</div><b>Week ${w}</b><p>${e(headline)}</p></a>`}return hero('2026 Weekly Write-Ups','Tuesday archives the finished week. Thursday publishes the next preview without erasing the recap.')+sec('Week 1 Results Recap',`<article class="writeup-copy"><h3>${e(T.headline)}</h3><p>${e(T.recapIntro)}</p>${T.gameRecaps.map(g=>`<h3>${e(g.a)} ${f(g.sa)} — ${f(g.sb)} ${e(g.b)}</h3><p>${e(g.copy)}</p>`).join('')}</article>`,'','CURRENT ARCHIVE')+sec('Every week gets receipts',`<div class="week-grid">${cards}</div>`,'','THE ARCHIVE')}
function week(){const w=Number(Q.get('week')||1);if(w===1)return hero('Week 1 — Results Recap',T.headline,'2026 WEEK 1 · FINAL')+sec('The week in full',`<article class="writeup-copy"><p>${e(T.recapIntro)}</p></article>${finalCards()}`,'','THE RECEIPTS')+sec('Weekly superlatives',awards(),'','WEEKLY HARDWARE')+sec('Lineup receipts',lineupTable(),'Optimal lineup analysis is a decision-quality tool, not the headline for every matchup.','START / SIT')+sec('Early Week 2 Yahoo board',week2Table(),'Makers Week 2 score projections and winner picks lock Thursday after waivers.','NEXT UP');if(w===2)return hero('Week 2 — Early Board','Tuesday Yahoo projections are live. The full Week 2 preview and locked Makers picks publish Thursday.','2026 WEEK 2 · TUESDAY')+sec('Yahoo Tuesday projections',week2Table(),'These are provisional Yahoo projections, not the Thursday Makers picks.','EARLY BOARD')+sec('What each team needs',needsCards(),'Waiver priorities are based on the Week 1 results, current roster and Tuesday pool.','WAR ROOM');return hero(`Week ${w} — 2026`,'Write-up pending')+sec('Scheduled',card('Thursday / Tuesday workflow','This week will receive a preview before kickoff and a results recap after MNF.'))}
function powerPage(){return hero('Power Rankings & Index','Week 1 results are now part of the model. Preseason still matters, but it no longer owns the page.')+sec('Tuesday Power Index',currentPowerTable(),T.powerMethod,'WEEK 1 CLOSED')+sec('Why everybody moved',`<div class="grid two">${T.power.map(x=>`<div class="card"><div class="rankline"><span class="rank-badge">#${x.rank}</span><span class="tag">${f(x.index,1)}</span></div><div class="kicker">${e(x.manager)} · ${e(x.record)} · PRE #${x.preRank}</div><h3>${e(x.team)}</h3><p><b>The case:</b> ${e(x.good)}</p><p><b>The check:</b> ${e(x.worry)}</p></div>`).join('')}</div>`,'','THE FILM ROOM')}
function oddsPage(){let rows=[...T.odds].sort((a,b)=>b.playoff-a.playoff).map((x,i)=>`<tr><td>${i+1}</td><td><b>${e(x.team)}</b><div class="small">${e(x.manager)} · ${e(standing(x.manager)?.record||'')}</div></td><td>${f(x.playoff,1)}%</td><td>${f(x.bye,1)}%</td><td>${f(x.title,1)}%</td><td>${f(x.toilet,1)}%</td><td>${f(x.expWins,2)}</td><td>${f(x.avgSeed,2)}</td><td>${e(x.seedRange)}</td></tr>`).join('');return hero('Playoff Odds','Week 1 is fixed as played. Every table below has been rerun for the Tuesday close.')+sec('Make the six-team bracket',barRows('playoff'),'Chance to finish in the championship field after fourteen regular-season games.','PLAYOFF PROBABILITY')+sec('First-round bye odds',barRows('bye'),'Top-two finish probability.','BYE EQUITY')+sec('Title equity',barRows('title'),'Simulated championship probability after qualifying and surviving the bracket.','CHAMPIONSHIP EQUITY')+sec('Toilet / punishment risk',barRows('toilet'),'Chance to finish dead last through the bottom-four bracket.','SHAME RISK')+sec('Full model board',`<div class="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>Playoff</th><th>Bye</th><th>Title</th><th>Toilet</th><th>Exp W</th><th>Avg seed</th><th>80% seed band</th></tr></thead><tbody>${rows}</tbody></table></div>`,T.modelMethod,'30,000-RUN TUESDAY MODEL')}
function raceDashboard(){return `<div class="grid two">${T.race.map(x=>card(x.teams,e(x.copy),x.tier)).join('')}</div>`}
function projectedField(){let p=T.projectedField;return `<div class="grid four">${card(p.byes.join('<br>'),'Top two','PROJECTED BYES')}${card(p.playoffs.slice(2).join('<br>'),'Seeds 3–6','PROJECTED FIELD')}${card(p.firstOut.join('<br>'),'First teams out','BUBBLE')}${card(p.danger.join('<br>'),'Early bottom risk','DANGER')}</div>`}
function stockTable(){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Franchise</th><th>Record</th><th>Price</th><th>Signal</th><th>Power</th><th>Playoff</th><th>Title</th><th>Shame</th></tr></thead><tbody>${T.stock.map(x=>`<tr><td>${x.rank}</td><td><b>${e(x.team)}</b><div class="small">${e(x.manager)}</div></td><td>${e(x.record)}</td><td><b>$${f(x.price,1)}</b></td><td><span class="stock ${x.signal.toLowerCase()}">${e(x.signal)}</span></td><td>${f(x.powerIndex,1)}</td><td>${f(x.playoff,1)}%</td><td>${f(x.title,1)}%</td><td>${f(x.toilet,1)}%</td></tr>`).join('')}</tbody></table></div>`}
function needsCards(){return `<div class="grid two">${T.needs.map(x=>`<div class="card"><div class="kicker">${e(x.priority)} PRIORITY · ${e(x.manager)}</div><h3>${e(x.team)} — ${e(x.need)}</h3><p>${e(x.copy)}</p><p><b>Targets:</b> ${e(x.targets)}</p></div>`).join('')}</div>`}
function standingsTable(){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>W-L</th><th>PF</th><th>PA</th><th>Streak</th><th>FAAB</th><th>Priority</th></tr></thead><tbody>${T.standings.map(x=>`<tr><td>${x.rank}</td><td><b>${e(x.team)}</b><div class="small">${e(x.manager)}</div></td><td>${x.w}-${x.l}</td><td>${f(x.pf)}</td><td>${f(x.pa)}</td><td>${e(x.streak)}</td><td>$${e(x.faab)}</td><td>${e(x.waiverPriority)}</td></tr>`).join('')}</tbody></table></div>`}
function pulse(){let p=T.weeklyPulse;return `<div class="grid four">${card(f(p.avg),'League average','WEEK 1')}${card(p.high,'New scoring record','HIGH SCORE')}${card(p.closest,'Closest finish','NAIL-BITER')}${card(p.blowout,'Largest margin','BLOWOUT')}</div><div class="notice" style="margin-top:18px"><b>Week 1 timeline:</b> ${e(T.timeline[0].copy)}</div>`}
function warroom(){return hero('2026 War Room','Week 1 is closed. This is the Tuesday state of the race, market, needs and Week 2 early board.')+`<section class="section"><div class="wrap"><div class="metric-grid"><div class="metric"><b>2</b><span>current week</span></div><div class="metric"><b>${f(T.weeklyPulse.avg)}</b><span>Week 1 league avg</span></div><div class="metric"><b>187.86</b><span>Week 1 high</span></div><div class="metric"><b>${T.prediction.modelRecord}</b><span>Makers model W-L</span></div><div class="metric"><b>${T.weeklyPulse.moves}</b><span>2026 moves logged</span></div></div></div></section>`+sec('Current standings',standingsTable(),'All ten Week 1 results reconciled to Yahoo.','THE TABLE')+sec('Race dashboard',raceDashboard(),'This is a Tuesday snapshot, not a season verdict.','ROAD TO WEEK 14')+sec('Projected field',projectedField(),T.modelMethod,'IF THE PLAYOFFS WERE PROJECTED TODAY')+sec('Franchise Stock Market',stockTable(),'Prices are a league-specific index built from current Power Index, playoff equity and title equity. Repriced every Tuesday.','WEEK 1 CLOSE')+sec('What everybody needs',needsCards(),'Updated from Week 1 performance, roster construction, FAAB and the current available-player pool.','WAR ROOM')+sec('Weekly pulse',pulse(),'The season timeline advances every Tuesday.','SEASON TIMELINE')+sec('Early Week 2 Yahoo board',week2Table(),'Makers picks lock Thursday.','NEXT WEEK')}
function predictionTable(){return `<div class="table-wrap"><table><thead><tr><th>Matchup</th><th>Makers pick</th><th>Yahoo pick</th><th>Actual</th><th>Makers</th><th>Yahoo</th><th>Yahoo margin error</th></tr></thead><tbody>${T.prediction.ledger.map(x=>`<tr><td><b>${e(x.teamA)}</b> ${f(x.scoreA)}<br>${e(x.teamB)} ${f(x.scoreB)}</td><td>${e(x.modelPick)} <span class="small">${f(x.modelProb,1)}%</span></td><td>${e(x.yahooPick)}<div class="small">${f(x.projA)}–${f(x.projB)}</div></td><td><b>${e(x.winner)}</b></td><td>${x.modelCorrect?'✓':'✕'}</td><td>${x.yahooCorrect?'✓':'✕'}</td><td>${f(x.yahooMarginError)}</td></tr>`).join('')}</tbody></table></div>`}
function week2Table(){return `<div class="table-wrap"><table><thead><tr><th>Matchup</th><th>Yahoo A</th><th>Yahoo B</th><th>Early favorite</th></tr></thead><tbody>${T.week2Yahoo.map(x=>`<tr><td><b>${e(x.teamA)}</b> vs <b>${e(x.teamB)}</b></td><td>${f(x.projA)}</td><td>${f(x.projB)}</td><td>${e(x.projA>x.projB?x.teamA:x.teamB)} by ${f(Math.abs(x.projA-x.projB))}</td></tr>`).join('')}</tbody></table></div>`}
function allPlayTable(){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>Week 1 all-play</th><th>Score</th><th>Actual</th></tr></thead><tbody>${T.allPlay.map(x=>{let s=standing(x.manager);return `<tr><td>${x.rank}</td><td><b>${e(x.team)}</b><div class="small">${e(x.manager)}</div></td><td>${x.w}-${x.l}</td><td>${f(x.score)}</td><td>${s.w}-${s.l}</td></tr>`}).join('')}</tbody></table></div>`}
function predictions(){return hero('Predictions','Week 1 results are graded. Tuesday publishes the early Week 2 Yahoo board; Makers Week 2 picks lock Thursday.')+`<section class="section"><div class="wrap"><div class="metric-grid"><div class="metric"><b>${T.prediction.modelRecord}</b><span>Makers model</span></div><div class="metric"><b>${T.prediction.yahooRecord}</b><span>Yahoo winners</span></div><div class="metric"><b>${f(T.prediction.yahooScoreMAE)}</b><span>Yahoo score MAE</span></div><div class="metric"><b>${f(T.prediction.yahooMarginMAE)}</b><span>Yahoo margin MAE</span></div><div class="metric"><b>1</b><span>shared miss</span></div></div></div></section>`+sec('Prediction Model Report Card',`<div class="grid three">${card('80.0%','4 correct winners in 5 games','MAKERS WINNER ACCURACY')}${card('80.0%','4 correct winners in 5 games','YAHOO WINNER ACCURACY')}${card('Billy over Nick','Both systems picked Nick. Billy won 103.70–97.86.','THE SHARED MISS')}</div><div class="notice" style="margin-top:18px">${e(T.prediction.note)}</div>`,'','WEEK 1 GRADED')+sec('Prediction ledger',predictionTable(),'Original Week 1 winner probabilities and Yahoo projections are preserved next to the actual results.','THE RECEIPTS')+sec('All-play standings',allPlayTable(),'A supporting lens for schedule luck — not the main character of every recap.','WEEK 1')+sec('Week 2 early Yahoo board',week2Table(),'Thursday adds the locked Makers score projections and picks.','NOT LOCKED YET')}
function lineupTable(){return `<div class="table-wrap"><table><thead><tr><th>Team</th><th>Actual</th><th>Optimal</th><th>Left</th><th>Eff.</th><th>Top starter</th><th>Top bench</th></tr></thead><tbody>${T.lineupAnalytics.map(x=>`<tr><td><b>${e(x.team)}</b><div class="small">${e(x.manager)}</div></td><td>${f(x.actual)}</td><td>${f(x.optimal)}</td><td>${f(x.left)}</td><td>${f(x.efficiency,1)}%</td><td>${e(x.topStarter)}</td><td>${e(x.topBench)}</td></tr>`).join('')}</tbody></table></div>`}
function roiTable(){return `<div class="table-wrap"><table><thead><tr><th>Manager</th><th>Team</th><th>Moves</th><th>Acquired pts</th><th>Pts / move</th><th>Grade</th><th>Receipt</th></tr></thead><tbody>${T.roi.map(x=>`<tr><td><b>${e(x.manager)}</b></td><td>${e(x.team)}</td><td>${x.moves}</td><td>${f(x.points)}</td><td>${f(x.pointsPerMove)}</td><td><b>${e(x.grade)}</b></td><td>${e(x.receipt)}</td></tr>`).join('')}</tbody></table></div>`}
function acquisitionTable(){return `<div class="table-wrap"><table><thead><tr><th>Manager</th><th>Player</th><th>Move</th><th>W1 pts</th><th>Role</th><th>Receipt</th></tr></thead><tbody>${T.acquisitionReceipts.map(x=>`<tr><td>${e(x.manager)}</td><td><b>${e(x.player)}</b></td><td>${e(x.move)}</td><td>${f(x.week1)}</td><td>${e(x.role)}</td><td>${e(x.receipt)}</td></tr>`).join('')}</tbody></table></div>`}
function analytics(){return hero('Analytics','Week 1 actuals, lineup decisions, schedule luck and front-office receipts are now live.')+sec('Weekly pulse',pulse(),'','WEEK 1')+sec('All-play standings',allPlayTable(),'TomD went 9-0 and Max 0-9 in the opening all-play table. Use it to understand schedule luck, not to rewrite every game result.','SCHEDULE CONTEXT')+sec('Lineup autopsy',lineupTable(),'TomD and Billy were 100% optimal. Nick left a league-high 22.00 points unused.','DECISION QUALITY')+sec('Activity efficiency',roiTable(),'Acquired-player Week 1 output divided by 2026 moves. This will become more meaningful as the sample grows.','FRONT OFFICE')+sec('Acquisition receipts',acquisitionTable(),'Actual Week 1 production from notable acquisitions.','THE TAPE')}
function transactions(){let activity=`<div class="activity-feed">${T.transactions.map(x=>`<div class="activity-card"><div><span class="activity-type">${e(x.type)}</span><strong>${e(x.manager)} · ${e(x.team)}</strong></div><p>${e(x.description)}</p><small>${e(x.time)}</small></div>`).join('')}</div>`;return hero('Moves & League Activity','The 2026 tape now includes all 17 structured transactions collected through Tuesday.')+sec('Activity tape',activity,'Yahoo duplicate wrapper rows are excluded.','17 STRUCTURED MOVES')+sec('Transaction ROI & Front-Office Grades',roiTable(),'Week 1 production from acquired players, with the sample-size warning it deserves.','ACTIVITY EFFICIENCY')+sec('Acquisition receipts',acquisitionTable(),'','WHO PAID OFF')}
function availableTables(){return Object.entries(T.topAvailable).map(([pos,arr])=>`<div class="card"><div class="kicker">${e(pos)}</div><div class="table-wrap"><table><thead><tr><th>Player</th><th>W2</th><th>Ros%</th></tr></thead><tbody>${arr.map(p=>`<tr><td><b>${e(p.name)}</b><div class="small">${e(p.nflTeam)} ${p.opponent?'vs '+e(p.opponent):''} ${p.status?'· '+e(p.status):''}</div></td><td>${f(p.projected)}</td><td>${e(p.rosteredPct)}%</td></tr>`).join('')}</tbody></table></div></div>`).join('')}
function waivers(){return hero('Waiver Wire','Tuesday recommendations from the validated 100-player available pool, current FAAB and Week 1 needs.')+sec('What everybody needs',needsCards(),'','TEAM-BY-TEAM')+sec('Best available by position',`<div class="grid two">${availableTables()}</div>`,'Availability reflects the Tuesday collector and can change before waivers process.','100-PLAYER POOL')+sec('FAAB & priority',standingsTable(),'Standings table includes current remaining FAAB and reverse-standings waiver priority.','MONEY LEFT')}
function schedulePage(){let cards=T.power.map(p=>{let r=resultForTeam(p.team),w2=week2ForTeam(p.team),rows=[];for(let w=1;w<=14;w++){let game=(D.schedule2026?.[String(w)]||[]).find(g=>g.includes(p.team));if(!game)continue;let opp=game[0]===p.team?game[1]:game[0];let status='';if(w===1&&r)status=`<em class="result-pill ${r.result==='W'?'win':'loss'}">${r.result} ${f(r.for)}–${f(r.against)}</em>`;else if(w===2&&w2)status=`<em>${f(w2.proj)}–${f(w2.oppProj)} Yahoo</em>`;rows.push(`<a class="schedule-line${w===1?' big':''}" href="week.html?week=${w}"><span class="schedule-week">W${w}</span><span class="schedule-opponent"><b>${e(opp)}</b><small>${e(managerForTeam(opp))}</small></span><span class="schedule-tags">${status}</span></a>`)}return `<article class="schedule-team-card"><div class="schedule-team-head"><div><div class="kicker">${e(p.record)} · POWER #${p.rank}</div><h3>${e(p.team)}</h3><p>${e(p.manager)}</p></div></div>${rows.join('')}</article>`}).join('');return hero('2026 Schedule','Every Road to Week 14 now carries the Week 1 W/L receipt and advances to Week 2.')+sec('Every road to Week 14',`<div class="schedule-team-grid">${cards}</div>`,'Completed weeks stay visible permanently. Week 2 shows the current Tuesday Yahoo projection until Thursday preview lock.','TEAM-BY-TEAM')}
function ledgerRows(){let base=(D.leagueLedger||[]).map(x=>({...x}));let mm=base.find(x=>x.record==='Most moves, modern archive');if(mm){mm.holder='Jim';mm.number='262';mm.receipt='2022–Week 1 2026. Week 1 added three more moves to the career churn lead.'}base.push({record:'Most career regular-season wins',holder:'Max',number:'33',receipt:'Modern archive through Week 1, 2026.'});base.push({record:'Most career regular-season points',holder:'TomD',number:'6,123.51',receipt:'Modern archive through Week 1, 2026; Week 1 record score pushed TomD into the PF lead.'});base.push({record:'Highest regular-season weekly score',holder:'TomD',number:'187.86',receipt:'Week 1, 2026: The Mustache riders 187.86, Pump and Go 107.46.'});return base}
function recordsPage(){let meta=Object.fromEntries((D.records||[]).map(r=>[r.manager,r]));let rows=[...T.career].sort((a,b)=>b.w-a.w||b.pct-a.pct).map((r,i)=>{let h=meta[r.manager]||{};return `<tr><td>${i+1}</td><td><b>${e(r.manager)}</b></td><td>${r.w}-${r.l}</td><td>${f(r.pct,1)}%</td><td>${f(r.pf)}</td><td>${f(r.pa)}</td><td>${h.titles??0}</td><td>${h.finals??0}</td><td>${r.moves}</td></tr>`}).join('');let led=ledgerRows().map(x=>`<tr><td>${e(x.record)}</td><td>${e(x.holder)}</td><td><b>${e(x.number)}</b></td><td>${e(x.receipt)}</td></tr>`).join('');return hero('Record Book','Week 1 has been audited against the modern archive.')+sec('Week 1 record audit',`<div class="notice red"><b>NEW RECORD:</b> TomD / The Mustache riders — 187.86, highest modern-era regular-season weekly score.</div><div class="grid two" style="margin-top:18px">${T.recordAudit.checked.map(x=>card(x,'Checked; existing record remains.','AUDITED')).join('')}</div><p class="small">${e(T.recordAudit.note)}</p>`,'','TUESDAY AUDIT')+sec('Career standings',`<div class="table-wrap"><table><thead><tr><th>#</th><th>Manager</th><th>W-L</th><th>Win%</th><th>PF</th><th>PA</th><th>Titles</th><th>Finals</th><th>Moves</th></tr></thead><tbody>${rows}</tbody></table></div>`,'Week 1 2026 is included. Billy remains separate from El Rubio.','MODERN ERA')+sec('League ledger',`<div class="table-wrap"><table><thead><tr><th>Record</th><th>Holder</th><th>Number</th><th>Receipt</th></tr></thead><tbody>${led}</tbody></table></div>`,'','BEST, WORST & WEIRDEST')}
function franchises(){let rec=Object.fromEntries(T.career.map(x=>[x.manager,x]));return hero('Franchise Files','2026 Week 1 results, current power and current needs are now attached to every active franchise.')+sec('Current franchises',`<div class="grid two">${(D.franchises||[]).filter(x=>x.manager!=='El Rubio').map(x=>{let r=rec[x.manager],p=power(x.manager),o=odds(x.manager),ne=need(x.manager),res=resultForTeam(x.current);return `<a class="card franchise" href="franchise.html?manager=${encodeURIComponent(x.manager)}"><div class="kicker">${e(x.manager)} · ${e(standing(x.manager)?.record||'')}</div><h3>${e(x.current)}</h3><div class="stat">Power #${p?.rank||'—'} · ${f(p?.index||0,1)}</div><p>${res?`W1 ${res.result} ${f(res.for)}–${f(res.against)} vs ${e(res.opp)}.`:''}</p><p><b>Playoff:</b> ${f(o?.playoff||0,1)}% · <b>Need:</b> ${e(ne?.need||'—')}</p></a>`}).join('')}</div>`,'','THE LIVE LEDGER')}
function franchise(){let m=Q.get('manager')||'Andrew',fr=(D.franchises||[]).find(x=>x.manager===m),r=T.career.find(x=>x.manager===m),p=power(m),o=odds(m),ne=need(m),res=fr?resultForTeam(fr.current):null,w2=fr?week2ForTeam(fr.current):null;if(!fr)return hero('Franchise not found');return hero(`${m} — ${fr.current}`,'Modern franchise history plus the live 2026 Tuesday state.')+`<section class="section"><div class="wrap profile-top"><div class="profile-box"><div class="big-record">${r?`${r.w}-${r.l}`:'—'}</div><p>${r?`${f(r.pct,1)}% modern-era win rate · ${f(r.pf)} PF · ${r.moves} moves`:''}</p><p>${e(fr.profile||'')}</p>${res?`<div class="notice"><b>Week 1:</b> ${res.result} ${f(res.for)}–${f(res.against)} vs ${e(res.opp)}.</div>`:''}</div><div class="callout"><div class="kicker">2026 POWER #${p?.rank||'—'} · INDEX ${f(p?.index||0,1)}</div><h3>${e(fr.current)} · ${e(standing(m)?.record||'')}</h3><p>${e(p?.good||'')}</p></div></div></section>`+sec('Tuesday dashboard',`<div class="grid four">${card(`${f(o?.playoff||0,1)}%`,'Playoff probability','PLAYOFF')}${card(`${f(o?.title||0,1)}%`,'Title equity','TITLE')}${card(ne?.need||'—',e(ne?.copy||''),'CURRENT NEED')}${card(w2?f(w2.proj):'—',w2?`vs ${e(w2.opp)} · opp ${f(w2.oppProj)}`:'','W2 YAHOO')}</div>`)+sec('Current scouting note',`<div class="grid two">${card('The case',e(p?.good||''))}${card('The check',e(p?.worry||''))}</div>`)}
const routes={home,weeks,week,power:powerPage,odds:oddsPage,transactions,waivers,schedule:schedulePage,records:recordsPage,franchises,franchise,warroom,predictions,analytics};
function injectStyles(){let s=document.createElement('style');s.textContent=`.stock{font-weight:900;padding:4px 8px;border-radius:999px}.stock.buy{background:#e7f7ea;color:#146c2e}.stock.hold{background:#f3efd9;color:#685d0a}.stock.sell{background:#fde7e7;color:#9a1f1f}.result-pill{font-style:normal;font-weight:900;padding:4px 7px;border-radius:999px}.result-pill.win{background:#e6f6e8;color:#156b2c}.result-pill.loss{background:#fde9e9;color:#9c2222}.odds-row strong small{display:block;font-weight:400;opacity:.6}.pagehead p{max-width:850px}.card p{line-height:1.5}`;document.head.appendChild(s)}
const page=document.body.dataset.page||'home';injectStyles();document.body.innerHTML=nav()+(routes[page]||home)()+foot();
const hamb=document.querySelector('.hamb'),nn=document.querySelector('.nav');if(hamb)hamb.addEventListener('click',()=>nn.classList.toggle('open'));
const here=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===here)a.classList.add('active')});
})();